### ISSUE TITLE
[EPIC] Release Gravitino 0.3.1

### ISSUE THREAD

**Issue by jerryshao** [datastrato/gravitino#1285]
### Describe the proposal

Since the release of 0.3.0, we have fixed several bugs related to code and documentation. So it would be better to have a minor release for 0.3.1.

### Task list

- [x] Track and make sure all the issues/bugs are fixed.
- [x] Create 0.3.1 tag
- [x] Upload binary packages
- [x] Update the playground and release related images.
- [x] publish to the maven repo
- [x] Update the doc to the website
- [x] Make a release note
