### ISSUE TITLE
[EPIC] Release Gravitino 0.4.0

### ISSUE THREAD

**Issue by jerryshao** [datastrato/gravitino#1821]
### Describe the proposal

This issue tracks all the works that should be done to release the Gravitino 0.4.0.

### Task list

- [x] branch cut and release preparation work. @jerryshao 
- [ ] #1804 @justinmclean 
- [x] fix the current CVEs @FANNG1 
- [x] source and package release @jerryshao 
- [x] Image release and playground update @qqqttt123 
- [x] maven repo publish. @yuqi1129 
- [x] javadoc @yuqi1129 
- [x] doc publish @ch3yne 
- [x] release notes @jerryshao 
- [x] blog post @jerryshao 
- [x] Publish release message to Slack and other community channel @xunliu
