### ISSUE TITLE
[Epic] Python client implementation for Graviton

### ISSUE THREAD

**Issue by xunliu** [datastrato/gravitino#2113]
### Describe the proposal

This issue tracks the work of implementing the Python client for Graviton. With this Python client, Data scientists could manipulate metadata from Graviton to the underlying systems.

### Task list

- [ ] Proposal design document
    - [ ] Python library management
    - [ ] ...
- [ ] Design and implement Python client Metalake APIs
- [ ] Design and implement Python client Catalog APIs
- [ ] Design and implement Python client Schema APIs
- [ ] Design and implement Python client Table APIs
- [ ] ...

**Comment by xunliu** [comment]
hi @SophieTech88 , @FrankYang0529 
Can you help me refine the [Proposal design document](https://docs.google.com/document/d/1Eq9qd94967cYpSagTps34vHbHNhO4VMPs4R-6tNK8Eo/edit) ?

**Comment by jerryshao** [comment]
CC @coolderli FYI

**Comment by jerryshao** [comment]
@noidname01 if you're interested in Python part, can you please continue working on the missing parts in Python to be feature consistent with Java, like table-related APIs. Thanks a lot.

**Comment by noidname01** [comment]
@jerryshao Sure, but after the meeting with @xunliu, we think that it's better to continue client-python feature development after Java client refactor has finished.
