### ISSUE TITLE
[EPIC] Release Gravitino 0.5.0

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#2941]
### Describe the proposal

This issue tracks all the works that should be done to release the Gravitino 0.5.0.

### Task list

- [x] branch cut and release preparation work. @yuqi1129 
- [x] License check @justinmclean 
- [x] source and package release @yuqi1129 
- [x] Image release and playground update @qqqttt123 
- [x] maven repo publish. @yuqi1129 
- [x] javadoc @yuqi1129 
- [x] doc publish @ch3yne 
- [x] release notes @yuqi1129  
- [x] Publish release message to Slack and other community channel @xunliu

**Comment by jerryshao** [comment]
As discussed with @xunliu offline, we plan to add python related codes in branch-0.5, and we also need to release python package to pypi. FYI @yuqi1129

**Comment by jerryshao** [comment]
@yuqi1129 please close this issue when everything is done.

**Comment by yuqi1129** [comment]
> @yuqi1129 please close this issue when everything is done.

Got it.
