### ISSUE TITLE
[EPIC] Catalog capability framework

### ISSUE THREAD

**Issue by mchades** [datastrato/gravitino#2952]
### Describe the proposal

Currently, we lack catalog-level capability management, which results in the need to duplicate some validation work across different catalogs.

### Task list

- [ ] framework design & POC #1661 
- [ ] introduce catalog capability framework with column not null #2819
- [ ] use the capability of column default value
- [ ] use the capability of name case-sensitive
- [ ] use the capability of name specification
- [ ] use the capability of managed storage
