### ISSUE TITLE
[EPIC] Supports StarRocks catalog

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#3302]
### Describe the proposal

Currently, we have made the Doris catalog accessible in Gravitino, as StarRocks is also used by many users, we need to support it as well. 
Since they share the same code bases, most of the features are the same, I think we can 
- Make Doris catalog connect to the StarRocks data source.
-Or we need to provide support for the StarRocks catalog. 

### Task list

- [ ] Support StarRocks catalog in web UI
- [ ] Make StarRocks table-related operation ready to use
- [ ] Check the StarRocks and Doris column type system.

**Comment by yuqi1129** [comment]
> Has this issue started development yet?

Not yet. If you are interested in it, you can give it a try or share your thoughts on it.

**Comment by zhangxuan183** [comment]
OK,thanks

**Comment by liunaijie** [comment]
Hi @yuqi1129, I am interested on this, could you assign it to me, thx~

**Comment by yuqi1129** [comment]
@liunaijie 
Thanks for your participation. The community has also been working on it recently. Please keep me informed about the progress if you have been working on it. Thank you.

**Comment by liunaijie** [comment]
> [@liunaijie](https://github.com/liunaijie) Thanks for your participation. The community has also been working on it recently. Please keep me informed about the progress if you have been working on it. Thank you.

@yuqi1129 Thanks for your replay, I am not started yet. If the community is working on this, I am looking forward on this feature.

 In my company, we use starrocks, hive, mysql, kafka. 
And I find the starrocks is not support, and starrocks is similar with Doris. So I want implement this catalog refer the Doris implement.

**Comment by yuqi1129** [comment]
Yeah, we have not start yet and welcome your contribution.

**Comment by yuqi1129** [comment]
@liunaijie 
I have raised a skeleton PR for StarRocks catalog. Would you like to handle the rest? You can refer to Doris catalog.

**Comment by yuqi1129** [comment]
@taylor12805, @liunaijie, do you guys have time to start working on https://github.com/apache/gravitino/issues/7675 within this week? If you don't have free time, I will do it myself, as we plan to release this feature in 1.0.0 and it's approaching.

**Comment by liunaijie** [comment]
> [@taylor12805](https://github.com/taylor12805), [@liunaijie](https://github.com/liunaijie), do you guys have time to start working on [#7675](https://github.com/apache/gravitino/issues/7675) within this week? If you don't have free time, I will do it myself, as we plan to release this feature in 1.0.0 and it's approaching.

Yes, I am still working on it. I think I can finish the first version code within this week.

BTW, When do we plan to release version 1.0.0?

**Comment by yuqi1129** [comment]
> Yes, I am still working on it. I think I can finish the first version code within this week.

It might be in three weeks or so.

**Comment by yuqi1129** [comment]
@liunaijie 
I have inquired about the proper version of StarRocks, and 3.3.x is the best one.

**Comment by liunaijie** [comment]
@yuqi1129 I am writing the test case, find the integration test need run docker to test it. 
I have a question is how to build image `apache/gravitino-ci:starrocks-0.1.0` like `apache/gravitino-ci:doris-0.1.5`

**Comment by yuqi1129** [comment]
@liunaijie 
You can refer to what Doris did here 

<img width="1547" height="1004" alt="Image" src="https://github.com/user-attachments/assets/07cd372f-2c19-4eca-a419-d080ceb1fa2d" />

I believe you can first raise PR to create a gravitino starrock image. After the PR is merged, we will help to release the image. For now, you can use `starrocks/allin1-ubuntu` to test locally currently.

**Comment by liunaijie** [comment]
> [@liunaijie](https://github.com/liunaijie) You can refer to what Doris did here
> 
> <img alt="Image" width="1547" height="1004" src="https://private-user-images.githubusercontent.com/15794564/467852488-07cd372f-2c19-4eca-a419-d080ceb1fa2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMxNDc1NTQsIm5iZiI6MTc1MzE0NzI1NCwicGF0aCI6Ii8xNTc5NDU2NC80Njc4NTI0ODgtMDdjZDM3MmYtMmMxOS00ZWNhLWE0MTktZDA4MGNlYjFmYTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzIyVDAxMjA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZjRkODk5NmFiZGJiNTMwNWVmZGUxNWM3MzFmODNkNTRjODdiZjZlYjBmMTU2NjlhMDE4ZDc0NDQ3YjQ0ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dvnf5GRRNTFZLPObtHQQ-Zdau_bTBgpoOt-PtNC3f8M">
> I believe you can first raise PR to create a gravitino starrock image. After the PR is merged, we will help to release the image. For now, you can use `starrocks/allin1-ubuntu` to test locally currently.


Hi @yuqi1129 I check the E2E, It looks I don't need to build the `apache/gravitino-ci:starrocks` image, I refer other connectors like `MySQLContainer` , set the image to `starrocks/allin1-ubuntu` directly
