### ISSUE TITLE
[EPIC] Improve the user authentication system

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#3327]
### Describe the proposal

Currently, we only implement authentication between the Gravitino client and the Gravitino server and the Gravitino server and Hive Metastore, catalogs such as Iceberg, HDFS, and Kafka are left unauthenticated. Additionally, there is no authentication between The Trino connector, Spark connector, and the Gravitino server, we need to improve it. 

### Task list

- [ ] Authentication between Gravitino and specific catalogs
    - [ ] Authentication between Iceberg catalog and Gravitino.
    - [ ] Authentication between the Hadoop catalog and Gravitino.
    - [ ] Authentication between Kafka and Gravitino.
- [ ] Trino connector authentication
    - [ ] Use authentication between Trino and Gravitino.
    - [ ] Support authentication between Trino and Hive/Iceberg
- [ ] Spark connector authentication
    - [ ] Use authentication between Trino and Gravitino
    - [ ] Support authentication between Trino and Hive/Iceberg
