### ISSUE TITLE
[EPIC] Gravitino Trino connector loads the catalog using Trino's dynamic catalog feature

### ISSUE THREAD

**Issue by diqiu50** [datastrato/gravitino#3524]
### Describe the proposal

In the current implementation, the Gravitino Trino connector cannot working on the Trino worker node.
So, we have a new solution to solve this issue by using Trino's dynamic catalog feature
[Loading catalog by Trino dynamic catalog manager](https://docs.google.com/document/d/1du7HOUpSzVImWcwyR_ddyTn2yRXZXfirCWOR19-ucyw/edit#heading=h.3nly3sywiywy)

### Task list

 - [x] #3526
 - [x] #3587
 - [x] #3630
 - [x] #3601
 - [x] #3683
 - [ ] #3632
 - [x] #3680
 - [ ] Bug can not support catalog name with metalake
 - [ ] Bug EXPLAIN command can not show query optimize details
 - [ ] Bug can not support Trino DevelopmentServer startup mode
