### ISSUE TITLE
[EPIC] Release Gravitino 0.5.1

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#3563]
### Describe the proposal

This issue tracks all the works that should be done to release the Gravitino 0.5.1.

### Task list

- [x] branch cut and release preparation work. @FANNG1 
- [x] #3574
- [x] source and package release @FANNG1  
- [x] Image release and playground update @qqqttt123 
- [x] maven repo publish. @yuqi1129 
- [x] javadoc @yuqi1129 
- [x] doc publish @ch3yne 
- [x] integration test of Gravitino release package. @danhuawang 
- [x] release notes @FANNG1   
- [x] Publish python client @xunliu 
- [ ] Publish release message to Slack and other community channel @xunliu
