### ISSUE TITLE
[EPIC] Optimize CI 

### ISSUE THREAD

**Issue by mchades** [datastrato/gravitino#3834]
### Describe the proposal

The current CI-triggered pipelines are too many, taking a long time to queue and execute, and need optimization.

### Task list

- [ ] optimize CI single job (use gradle cache,  minimize dependency changes, and reuse intermediate compilation results)
- [ ] reuse docker env in Gravitino tests
- [ ] resue docker env in Engine tests(such as Spark, Trino and Flink)
- [ ] remove multiply JDK env test from PR CI to nightly CI (notification mechanism needed)
