### ISSUE TITLE
[EPIC] Refactor EnityStore to make it more user-friendly

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#3855]
### Describe the proposal

As we are going to support privileges and tag systems, more and more types of data need to be stored in Gravitino such as relation data, and graph data. However, the Gravitino entity store system is not well designed to meet these needs, so we should try to refactor the Enity store system, there are mainly the following things to be considered: 

1. Let's refactor KvEntityStore to handle more storage scenarios
2. Polish JDBC EntityStore to make it more stable and support more databases like PG, and Oracle.
3. Improving the interface `EntityStore`.

### Task list

- [ ] Optimize KV entity store to support complex data type
- [ ] Support other's JDBC database as JDBC backend
   - [ ] Support embedded JDBC databases like Derby, SQLite and MariaDB Emebeded or so
   - [ ] Support PG
   - [ ] Support Oracle
- [ ] Optimize interface `EntityStore` to support complicated scenarios
- [ ] Optimize current table structure for MySQL backend
