### ISSUE TITLE
[EPIC] Make Gravitino open source community ready

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#664]
### Describe the proposal

Tasks that need to be done to get ready to open source Gravitino.

### Task list

- [x] #683
- [x] #688
- [x] #685
- [x] Check web UI for snippets and fix
- [x] #942
- [x] #708
- [x] #686
- [ ] #727
- [x] #725
- [x] #726
- [x] #789
- [x] #690
- [x] #689
- [x] #705
- [x] Add information on signing and submitting ICLAs (no longer needed)
- [x] #709
- [x] #946
- [ ] #943
- [x] #945
- [x] #748
- [x] #749
- [x] #944
- [x] #753
- [x] #790
- [x] Website updates for Gravitino
- [x] Add repo info to the website
- [x] Make repo public
- [x] Set license in GitHub (if needed)
